//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_N7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public int MaPhieu { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> SoLuongMuon { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public Nullable<System.DateTime> NgayTraSach { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
